#include "OpeningScene.h"

void OpeningScene::showOpening()
{
    cout << R"(
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkcc0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOoolcl0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOcckWMMMMMMWWWWWOlllllllc' .,lllllc:c::l0WWWWXd::::oKMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd..cXXXNNNkccccc::::::,'''''''''''......';;;;;ldoddxXMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN00o'.',:::ccccc:::::;;,,,,,,,,,,,,,,,,,........';coKMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd. .'cc:;;;;;,,,,,,,,,,,,;:::::;,,,,,,''...  .:ddxkkkkONMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxxl,,,,,;,,,''.......''';ccc:::::;'',,,'........  .,::::codkXMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd..;dddc;,,,,'..'''''',,;;:::::ccc:::'...........  .kMMMMNxldXMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWd...,,,,'';cc:;,;,,,;,,'';ccdkkkkkkkxl:;'......... .,:lKWWWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOc::cccclllll:,,,,,,,,,,,'..cxkkOkl;:dOkkkd,...........   ,:lOXNWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx..;xko:::oxx:...,,,,,,,,'.':ooxkkxddxkkdol'......... ...,d0ko:oKMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO:;:cccllllcc,...'''''...',,'..;ccloolcc,...........  .dXXWMWNXXWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWOlc,......',,'..',,'..',,,''................... .,:lKMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo.  ...,ccccc;..;cc,..;cc;''..............   .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKddddddc'',,,....,,....,,'...........        .,:l0WWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0do;........................   ...........',:kXXWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx..'::'........'::'............'..  ...........,d0KNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;,'..................     '::'..   ..........    'OMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWOcccc:,.....,::.      ....';c:.   ......  ...  .:oxXMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dodxdocc'.........',ldl.  ......   .....   .OMMMMMMMMMMMMMMM
MWOdddddddddddkNMMWX0XWMMMMMWK0NMMMMMNKKKWMMMMOcxNMMWNXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl  ....... .;lc,...  .....    ......  .,;l0NWWMMMMMMMMM
MWklll,   'cllxNMMNl.cXNNNNNO,.xMMMXo;;:;;dXMWo ;KMMXl.,ccccccccdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl........  .:do.   ........   .........   .'cKMMMMMMMMM
MNOxo:',c;';ldkXMMNc .:ccc:c;..dMMNc :KW0; lNWo ;XMMX; cXNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo........  .,c:.  .........   ........      .OMMMMMMMMM
W0l:cdxl'lkdl:cOWMNc ,kOOOOOd. dMM0'.xMMMx.,KWo ;XMMX; ;O000000O0NMMMMMMMMMMMMMMMMMMMMMMMMMMKkx;. . ....         ......     .....          .OMMMMMMMMM
0l:cccc,.,:cccccOMWo.,::'.,c:',kMMK, oWMWo ;XWo ;KMMNd,;::::::::lKMMMMMMMMMMMMMMMMMMMMMMMMMWl   .........      ........            ...     .OMMMMMMMMM
WXkc::::::::::xKNMMNXXXO' lXXXNWMMWk'.cdc.,OWWo ;KMMMWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMW0ol,               .....          ........     .OMMMMMMMMM
MMx..cdddddl. oWWOlllcl:. 'clllcoKMMXxllokXMMMo ;XNxccccccccccccccdXMMMMMMMMMMMMMMMMMMMMMMMWk;;.  ......      .......      ...........     .OMMMMMMMMM
MMx..;ccccc:..dMWKxxxxxxxkxxxxxxkXMMMMMMMMMMMWd ;XW0kkkkkkkkkkkkkk0NMMMMMMMMMMMMMMMMMMMMMMMWl   ...,,...   ...''',,,''..     ........    ..;0MMMMMMMMM
MMN0OOOOOOOOO0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXk0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd''.........   .,,.....'','...   ';;;;,'... .coxXMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNx:;.  ...   .,'.     ...  .,;l0WNNWKdc:...  .lxxxxxxxON
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkcccc:.   ..   ...     .kWMMMNkooooc.      .   .;cdN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNd:::::::::::::;.          .,::::lKWWWWWWWWMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxlllllllllldXMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                                              MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM       최후의 시간이다. 이것은 당신이 살아남은 마지막 이야기.      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                                              MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
)" << endl;
}